name: main
channels:
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - pandas
  - numpy
  - plotly
  - py-xgboost
  - pip
  - pip:
    - hipe4ml
    - optuna
    - fasttreeshap
    - kaleido
